genesis-file = "genesis.json"
data-path = "/var/lib/besu"
rpc-http-enabled = true
rpc-http-api = ["ETH", "NET", "WEB3"]
rpc-http-host = "127.0.0.1"
rpc-http-port = 8545
rpc-ws-enabled = false
rpc-ws-host = "127.0.0.1"
rpc-ws-port = 8546
p2p-enabled = true
p2p-host = "0.0.0.0"
p2p-port = 30303
min-gas-price = 0